object_base: orig/GUNE5D
object: sys/main.dol
hash: 7CBA77AA496EB0FC5FFEC60EFD9680AA9635D679
symbols: config/GUNE5D/symbols.txt
splits: config/GUNE5D/splits.txt

mw_comment_version: 8
scrub_extab: true

modules: []
